spring:
  profiles:
    active: dev
  config:
    import:
      - optional:file:.env[.properties]
      - classpath:config/ai.yml
      - classpath:config/kafka.yml
  main:
    web-application-type: servlet
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false # 프로젝트 실행 시 자동으로 배치 실행되게 하고 싶으면 true로 변경
api:
  service-key: ${SERVICE_KEY}
data:
  elasticsearch:
    schema-management:
      create-index: false
      create-mappings: false
api-url:
  adoption: ${ADOPTION_URL}
  shelter: ${SHELTER_URL}