spring:
  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  elasticsearch:
    uris: ${ELASTICSEARCH_URI}
  jpa:
    hibernate:
      ddl-auto: update